=== NOAA-PMEL/SOCAT/trunk/SanityChecker/xml_specs/SanityChecker_ColumnInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="SanityChecker_ColumnInfo"
	elementFormDefault="qualified" xmlns:SanityCheckercolinfo="SanityChecker_ColumnInfo">

	<!-- This is the XML definition for the output of the SanityChecker for SOCAT. The output 
	  contains details of all the warnings, errors and	other messages produced by the Sanity 
	  Checker while processing an input data file. Any program calling the SanityChecker 
	  must expect an XML document of this specification to be made available in a location 
	  specified by the calling program. -->

  <!-- Root element -->
	<element name="column_info" type="SanityCheckercolinfo:col_info"></element>

  <!-- Root element content -->
	<complexType name="col_info">
		<sequence>
			<element name="socat_column" type="SanityCheckercolinfo:socat_column"
				maxOccurs="unbounded" minOccurs="1">
			</element>
			<element name="date_columns"
			  type="SanityCheckercolinfo:date_cols" maxOccurs="1" minOccurs="1">
			  </element>
			</sequence>
	</complexType>

  <!-- Contents of the socat_column elements -->
	<complexType name="socat_column">
		<sequence>
 				<element name="input_column" type="SanityCheckercolinfo:input_col"
  				maxOccurs="1" minOccurs="1">
  				</element>
			<element name="input_units" type="string" maxOccurs="1" minOccurs="1"></element>
		  <element name="missing_value" type="double" maxOccurs="1" minOccurs="0"></element>
     </sequence>
   	<attribute name="name" type="string"></attribute>
	</complexType>
	
	  <!-- Contents of the date_columns element -->
	  <complexType name="date_cols">
	    <choice>
        <element name="date_time" type="SanityCheckercolinfo:input_col"></element>
        <sequence>
          <element name="date" type="SanityCheckercolinfo:input_col"></element>
          <element name="time" type="SanityCheckercolinfo:input_col"></element>
        </sequence>
        <sequence>
          <element name="year" type="SanityCheckercolinfo:input_col"></element>
          <element name="month" type="SanityCheckercolinfo:input_col"></element>
          <element name="day" type="SanityCheckercolinfo:input_col"></element>
          <element name="hour" type="SanityCheckercolinfo:input_col"></element>
          <element name="minute" type="SanityCheckercolinfo:input_col"></element>
          <element name="second" type="SanityCheckercolinfo:input_col"></element>
        </sequence>
	    </choice>
	  </complexType>
	  
	     <!-- Defintion of the col_info/socat_column/input_column element -->
    <complexType name="input_col">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="index" type="int"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>
</schema>

=== NOAA-PMEL/SOCAT/SanityChecker/src/test/resources/xml_specs/col_info_test2.xml
<?xml version="1.0" encoding="UTF-8"?>

<column_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="SanityChecker_ColumnInfo" xmlns:SanityChecker="SanityChecker_ColumnInfo" xsi:schemaLocation="SanityChecker_ColumnInfo SanityChecker_ColumnInfo.xsd">
  <socat_column name="latitude">
    <input_column index="1">lat</input_column>
		<input_units>dddmm.mmm</input_units>
	</socat_column>
<socat_column name="longitude">
		<input_column index="2">lon</input_column>
		<input_units>dddmm.mmm</input_units>
	</socat_column>
  <date_columns>
    <date index="3">date</date>
    <time index="4">time</time>
  </date_columns>
</column_info>

=== NOAA-PMEL/SOCAT/trunk/xml_specs/col_info_test3.xml
<?xml version="1.0" encoding="UTF-8"?>

<column_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="SanityChecker_ColumnInfo" xmlns:SanityChecker="SanityChecker_ColumnInfo" xsi:schemaLocation="SanityChecker_ColumnInfo SanityChecker_ColumnInfo.xsd">
  <socat_column name="latitude">
    <input_column index="1">lat</input_column>
		<input_units>dddmm.mmm</input_units>
	</socat_column>
<socat_column name="longitude">
		<input_column index="2">lon</input_column>
		<input_units>dddmm.mmm</input_units>
	</socat_column>
  <date_columns>
    <year index="3">date</year>
    <month index="3">date</month>
    <day index="3">date</day>
    <hour index="3">date</hour>
    <minute index="3">date</minute>
    <second index="3">date</second>
  </date_columns>
  </column_info>

=== NOAA-PMEL/SOCAT/trunk/Testing/input/NOPACCS_NH95-2.csv.xml
<?xml version="1.0" encoding="UTF-8"?>
<column_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="SanityChecker_ColumnInfo" xmlns:dup="SanityChecker_ColumnInfo" xsi:schemaLocation="SanityChecker_ColumnInfo SanityChecker_ColumnInfo.xsd">
  <socat_column name="latitude">
    <input_column index="4">Lat(degN)</input_column>
    <input_units>decimal_degrees</input_units>
  </socat_column>
  <socat_column name="longitude">
    <input_column index="5">Lon(degE)</input_column>
    <input_units>decimal_degrees</input_units>
  </socat_column>
  <socat_column name="temp">
    <input_column index="6">Tss(degC)</input_column>
    <input_units>degC</input_units>
  </socat_column>
  <socat_column name="temperature_equi">
    <input_column index="7">Equilibrator Temperature(degC)</input_column>
    <input_units>degC</input_units>
  </socat_column>
  <socat_column name="sal">
    <input_column index="8">Sal.</input_column>
    <input_units>psu</input_units>
  </socat_column>
  <socat_column name="pressure_equi">
    <input_column index="9">EquilibratorPressure(hPa)</input_column>
    <input_units>hPa</input_units>
  </socat_column>
  <socat_column name="xco2water_eq_dry">
    <input_column index="10">X(CO2)w(ppm)</input_column>
    <input_units>ppm</input_units>
  </socat_column>
  <socat_column name="fco2water_sst_wet">
    <input_column index="11">fCO2w(uatm)</input_column>
    <input_units>uatm</input_units>
  </socat_column>
  <socat_column name="xco2air_dry">
    <input_column index="12">X(CO2)a(ppm)</input_column>
    <input_units>ppm</input_units>
  </socat_column>
  <socat_column name="fco2air_wet">
    <input_column index="13">fCO2a(uatm)</input_column>
    <input_units>uatm</input_units>
  </socat_column>
  <date_columns>
    <date index="2">Date(UTC)</date>
    <time index="3">Time(UTC)</time>
  </date_columns>
</column_info>
