=== NOAA-PMEL/SOCAT/SanityChecker/xml_specs/SanityChecker_Output.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="SanityChecker_Output"
	elementFormDefault="qualified" xmlns:SanityCheckeroutput="SanityChecker_Output">

	<!-- This is the XML definition for the output of the Data Upload Processor
		(SanityChecker) for SOCAT. The output contains details of all the warnings, errors and
		other messages produced by the SanityChecker while processing an input data file.
		Any program calling the SanityChecker must expect an XML document of this specification
		to be made available in a location specified by the calling program. -->

  <!-- Root element -->
	<element name="SanityChecker_output" type="SanityCheckeroutput:SanityChecker_output"></element>

  <!-- Root element content -->
	<complexType name="SanityChecker_output">
		<sequence>
			<element name="file_summary" type="SanityCheckeroutput:file_summary"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="metadata_messages"
			  type="SanityCheckeroutput:metadata_messages" maxOccurs="1" minOccurs="1">
			  </element>
			<element name="column_summary"
				type="SanityCheckeroutput:column_summary" maxOccurs="1" minOccurs="1">
			</element>
			<element name="data_messages" type="SanityCheckeroutput:data_messages"
				maxOccurs="1" minOccurs="1">
			</element>
		</sequence>
	</complexType>

  <!-- Contents of the file_summary element -->
	<complexType name="file_summary">
		<sequence>
		  <element name="metadata_lines" type="int" maxOccurs="1" minOccurs="1"></element>
			<element name="data_lines" type="int" maxOccurs="1" minOccurs="1"></element>
			<element name="metadata_message_counts"
				type="SanityCheckeroutput:metadata_message_counts" maxOccurs="1" minOccurs="1">
			</element>
			<element name="data_message_counts"
				type="SanityCheckeroutput:data_message_counts" maxOccurs="1" minOccurs="1">
			</element>
		</sequence>
	</complexType>

  <!-- Contents of the metadata_messages element -->
    <complexType name="metadata_messages">
      <sequence>
        <element name="message" type="SanityCheckeroutput:metadata_messages_message" maxOccurs="unbounded" minOccurs="0"></element>
      </sequence>
    </complexType>

<!-- Contents of the column_summary element -->
	<complexType name="column_summary">
		<sequence>
			<element name="column" type="SanityCheckeroutput:col_summary_column"
				maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
	</complexType>

  <!-- Contents of the file_summary/metadata_message_counts element -->
    <complexType name="metadata_message_counts">
    	<sequence>
    		<element name="critical" type="int" maxOccurs="1" minOccurs="1"></element>
    		<element name="error" type="int" maxOccurs="1" minOccurs="1"></element>
       <element name="unrecognised" type="int" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

  <!-- Contents of the file_summary/data_message_counts element -->
    <complexType name="data_message_counts">
    	<sequence>
    		<element name="critical" type="int" maxOccurs="1" minOccurs="1"></element>
    		<element name="error" type="int" maxOccurs="1" minOccurs="1"></element>
    		<element name="warning" type="int" maxOccurs="1" minOccurs="1"></element>
    		<element name="lines_with_errors" type="int" maxOccurs="1" minOccurs="1"></element>
    		<element name="lines_with_warnings" type="int" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

  <!-- Contents of the column_summary/column element -->
    <complexType name="col_summary_column">
    	<sequence>
    		<element name="message" type="SanityCheckeroutput:column_message" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    	<attribute name="pos" type="int"></attribute>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="errors" type="int"></attribute>
    	<attribute name="warnings" type="int"></attribute>
    </complexType>

  <!-- Contents of the column_summary/column/message element -->
    <complexType name="column_message">
    	<complexContent>
    		<extension base="SanityCheckeroutput:message_base">
    			<sequence>
    				<element name="count" type="int"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

  <!-- Contents of the data_messages element -->
    <complexType name="data_messages">
      <sequence>
        <element name="message" type="SanityCheckeroutput:data_messages_message" maxOccurs="unbounded" minOccurs="0"></element>
      </sequence>
    </complexType>

  <!-- Contents of the data_messages/messages/message element -->
    <complexType name="data_messages_message">
    	<complexContent>
    		<extension base="SanityCheckeroutput:message_base">
    			<sequence>
    				<element name="line" type="int" maxOccurs="1" minOccurs="1"></element>
    				<element name="column" type="SanityCheckeroutput:line_message_col"
    					maxOccurs="1" minOccurs="1">
    				</element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

<!-- Contents of the data_messages/messages/message element -->
    <complexType name="metadata_messages_message">
    	<complexContent>
    		<extension base="SanityCheckeroutput:message_base">
    			<sequence>
    				<element name="line" type="int" maxOccurs="1" minOccurs="1"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

<!-- Base definition of a 'message' element. Used in multiple places the XML -->
    <complexType name="message_base">
    	<sequence>
    		<element name="type" maxOccurs="1" minOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="Missing"></enumeration>
    					<enumeration value="Out of range"></enumeration>
    					<enumeration value="Unrecognised"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="properties" type="SanityCheckeroutput:message_properties"
    			maxOccurs="1" minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="severity">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="error"></enumeration>
    				<enumeration value="warning"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

  <!-- Contents of the message_properties element used in messages (see the message_base type -->
  <!-- Contains various extra information that can help the user to understand what's required, such as the valid data range. -->
    <complexType name="message_properties">
    	<sequence>
    		<element name="name" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="min" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="max" type="string" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <!-- Additional 'column' element used in data_message messages but not elsewhere -->
    <complexType name="line_message_col">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="pos" type="int"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>
</schema>

=== NOAA-PMEL/SOCAT/SanityChecker/xml_specs/dup_output_test.xml
<?xml version="1.0" encoding="UTF-8"?>

<SanityChecker_output xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="SanityChecker_Output" xmlns:SanityChecker="SanityChecker_Output" xsi:schemaLocation="SanityChecker_Output SanityChecker_Output.xsd">
  <file_summary>
    <metadata_lines>2</metadata_lines>
    <data_lines>50</data_lines>
    <metadata_message_counts>
      <critical>0</critical>
      <error>1</error>
      <unrecognised>3</unrecognised>
    </metadata_message_counts>
    <data_message_counts>
      <critical>0</critical>
      <error>12</error>
      <warning>22</warning>
      <lines_with_errors>12</lines_with_errors>
      <lines_with_warnings>15</lines_with_warnings>
    </data_message_counts>
  </file_summary>
  <metadata_messages>
   <message severity="warning">
     <type>Unrecognised</type>
     <properties>
       <name>Wind measurer thingy height</name>
     </properties>
     <line>1</line>
   </message>
   <message severity="warning">
     <type>Out of range</type>
     <properties>
       <name>intake_depth</name>
       <min>0</min>
       <max>20</max>
     </properties>
     <line>1</line>
   </message>
  </metadata_messages>
  <column_summary>
    <column pos="1" name="Latitude" errors="1" warnings="2">
      <message severity="error">
          <type>Missing</type>
          <count>1</count>
      </message>
      <message severity="warning">
        <type>Out of range</type>
        <properties>
          <min>-90</min>
          <max>90</max>
        </properties>
        <count>2</count>
      </message>
    </column>
    <column pos="2" name="Longitude" errors="1" warnings="2">
    </column>
  </column_summary>
  <data_messages>
    <message severity="error">
      <type>Missing</type>
      <line>5</line>
      <column pos="3">Date</column>
    </message>
    <message severity="warning">
      <type>Out of range</type>
      <properties>
        <min>25</min>
        <max>40</max>
      </properties>
      <line>12</line>
      <column pos="13">Salinity</column>
    </message>
  </data_messages>
</SanityChecker_output>
